version: "3.1"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-cubaengineer
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql-cubaengineer
    restart: unless-stopped
    ports:
      - 33006:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "cubaengineer" 
      MYSQL_USER: "cubaengineer"
      MYSQL_PASSWORD: "cubaengineer.pass"
      MYSQL_ROOT_PASSWORD: "root.pass"
      MYSQL_ROOT_HOST: "%"
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - laravel

  php:
    image: bjvalmaseda/laravel-devenv:0.1 #imagen compilada por mi 
    container_name: php-cubaengineer
    restart: unless-stopped #
    volumes: # carpeta de proyecto local
      - ./src:/var/www/html
    networks:
      - laravel # red
    expose:
      - 9000
networks: 
  laravel:

volumes:
  dbdata:
